version: '3.8'
services:
  client:
    container_name: client_dev
    # env_file: ./env_files/.env.development
    # stdin_open: true
    build:
      context: ./client
      dockerfile: Dockerfile.dev
    ports:
      - '3000:3000'
    networks:
      - mern-app
    volumes:
      - ./client/:/app
      - /app/node_modules
    command: bash -c "npm start"
  api:
    container_name: api_dev
    restart: always
    # env_file: ./env_files/.env.development
    build:
      context: ./server
      dockerfile: ./Dockerfile
    ports:
      - '3001:3001'
    networks:
      - mern-app
    volumes:
      - ./server/:/app
      - /app/node_modules
    depends_on:
      - mongo
    command: npx nodemon server.js
  mongo:
    container_name: mongo_dev
    image: mongo
    ports:
      - '27017:27017'
    networks:
      - mern-app
    volumes:
      - ./mongo/data:/data/db
networks:
  mern-app:
    driver: bridge
volumes:
  mongo-data:
    driver: local
