version: '3'
services:
  # nginx:
  #   container_name: nginx_prod
  #   restart: always
  #   build:
  #     dockerfile: Dockerfile
  #     context: ./nginx
  #   ports:
  #     - '80:80'
  mongo:
    container_name: mongo_prod
    image: mongo
    ports:
      - '27017:27017'
    volumes:
      - ./mongo/data:/data/db
  api:
    container_name: api_prod
    restart: always
    #env_file: ./env_files/.env.production
    # environment:
    #   PORT: 3001
    #   MONGO_URI: mongodb://mongo:27017/appnamehere

    build:
      dockerfile: Dockerfile
      context: ./server
    # volumes:
    #   - /app/node_modules
    #   - ./server:/app
    links:
      - mongo
    ports:
      - '3001:3001'
    depends_on:
      - mongo
  client:
    container_name: client_prod

    stdin_open: true
    build:
      dockerfile: Dockerfile.prod
      context: ./client
    ports:
      - '80:80'
    # volumes:
    #   - /app/node_modules
    #   - ./client:/app
    # env_file: ./env_files/.env.production
    # environment:
    #   REACT_APP_API_URL: 'http://192.168.1.98:3001/api'
    #   REACT_APP_REDIRECT: 'http://192.168.1.98:80'
    links:
      - api
volumes:
  mongo-data:
    driver: local
