version: '3'
services:
  mongo:
    container_name: mongo_prod
    image: mongo
    ports:
      - '27017:27017'
    volumes:
      - ./mongo/data:/data/db
  api:
    container_name: api_prod
    restart: always
    build:
      dockerfile: Dockerfile
      context: ./server
    links:
      - mongo
    ports:
      - '3001:3001'
    depends_on:
      - mongo
  client:
    container_name: client_prod
    stdin_open: true
    build:
      dockerfile: Dockerfile.prod
      context: ./client
    ports:
      - '80:80'
      - '443:443'
    links:
      - api
volumes:
  mongo-data:
    driver: local
