import mongoose from 'mongoose';

const userSchema = mongoose.Schema({
  // overrides auto id generated by mongoDB
  _id: {
    type: String,
    required: true,
  },
  username: {
    type: String,
    required: true,
  },
  email: {
    type: String,
    required: true,
    unique: true,
  },
});

export const User = mongoose.model('User', userSchema);